name: Docker Image CI

on:
  push:
    branches: 
      - "**"
  pull_request:
    branches: 
      - "**"

env:
  SERVICE_1_APP_NAME: "hw-ui-service"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build -t "${{ env.SERVICE_1_APP_NAME }}-${{ github.sha::7 }}-${{ github.ref_name }}" .
