apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-fe
  labels:
    name: hello-world-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-fe
  template:
    metadata:
      labels:
        app: hello-world-fe
    spec:
      containers:
      - name: hello-world-fe
        image: us-central1-docker.pkg.dev/nonprod-app-cluster/nonprod/hw-test-ab12n1o-develop:latest
        ports:
        - containerPort: 3080
        - containerPort: 3081
        env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "3080"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: dev-db-credentials
              key: host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: dev-db-credentials
              key: port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: dev-db-credentials
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dev-db-credentials
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: dev-db-credentials
              key: database
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "200m"
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
