apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-ui-ingress
spec:
  rules:
    - host: idme-helloworld.com  # Replace with your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world-ui-service
                port:
                  number: 80
