apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hello-world-fe-monitor
  labels:
    app: hello-world-fe
spec:
  selector:
    matchLabels:
      app: hello-world-fe
  namespaceSelector:
    matchNames:
      - default 
  endpoints:
    - port: metrics
      path: /metrics
      interval: 5s
