apiVersion: v1
kind: Service
metadata:
  name: hello-world-ui
  labels:
    service: hello-world-ui
spec:
  selector:
    app: node
  type: LoadBalancer
  ports:
    - port: 3080
      targetPort: 3080
