name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SERVICE_1_APP_NAME: "hw-ui-service"
    
jobs:
  build-service1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Show Short Git SHA
      run: echo "short_sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build -t "${{ env.SERVICE_1_APP_NAME }}-${{ env.short_sha }}-${{ github.ref_name }}" .
