name: Perform Precommit Steps

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: [ "main" ]

env:
  service_name: hw-ui-service
  
jobs:
  get-short-sha:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.get_sha.outputs.short_sha }}
    steps:
      - name: Show Short Git SHA
        id: get_sha
        run: echo "short_sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
        
  build:
    needs: [get-short-sha]
    uses: thunderbirdgit/gh-actions-wf/.github/workflows/nodejs-build.yml@main
    with:
      #service_name: "${{ env.service_name }}"
      service_name: "hw-ui-service"      
      short_sha: "${{ needs.get-short-sha.outputs.short_sha }}"
      branch_name: "${{ github.head_ref }}"
