name: Perform Precommit Steps

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: [ "main" ]
  
jobs:
  set-service-names:
    runs-on: ubuntu-latest
    steps:
      - name: Set Service Names
        id: set_service_names
        run: echo "service_name=hw-ui-service" >> $GITHUB_ENV
    
  determine-branch:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.get_branch.outputs.branch_name }}
    steps:
      - name: Get Branch Name
        id: get_branch
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            branch_name=${GITHUB_REF#refs/heads/}
            echo "branch_name=$branch_name" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "branch_name=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          fi

      - name: Print Final Branch Name
        run: |
          echo "Branch Name: ${branch_name}"
          
  get-short-sha:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.get_sha.outputs.short_sha }}
    steps:
      - name: Show Short Git SHA
        id: get_sha
        run: echo "short_sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
        
      - name: Print Short Git SHA
        run: |
          echo "Git SHA: ${short_sha}"
        
  build:
    needs: [get-short-sha, determine-branch]
    uses: thunderbirdgit/gh-actions-wf/.github/workflows/nodejs-build.yml@main
    with:
      service_name: ${{ service_name }}
      #service_name: "hw-ui-service"
      short_sha: ${{ needs.get-short-sha.outputs.short_sha }}
      branch_name: ${{ needs.determine-branch.outputs.branch_name }}
