name: Perform Precommit Steps

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: [ "main" ]

jobs:    
  determine-branch:
    uses: thunderbirdgit/gh-actions-wf/.github/workflows/get-branch-name.yml@main
          
  get-short-sha:
    uses: thunderbirdgit/gh-actions-wf/.github/workflows/get-short-sha.yml@main    
        
  build:
    strategy:
      matrix:
        service_name: ["hw-ui-service", "hw-ui-service2"]
    needs: [get-short-sha, determine-branch]    
    uses: thunderbirdgit/gh-actions-wf/.github/workflows/nodejs-build.yml@main
    with:
      service_name: ${{matrix.service_name}}      
      short_sha: ${{ needs.get-short-sha.outputs.short_sha }}
      branch_name: ${{ needs.determine-branch.outputs.branch_name }}      
