name: Perform Precommit Steps

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: [ "main" ]

env:
  service_name: hw-ui-service
  
jobs:
  determine-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Get Branch Name
        id: get_branch
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "Branch Name: ${{ github.ref }}"
            # Extract the branch name
            branch_name=${GITHUB_REF#refs/heads/}
            echo "Branch Name: $branch_name"
            echo "branch_name=$branch_name" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "Head Branch Name: ${{ github.head_ref }}"
            echo "head_branch_name=${{ github.head_ref }}" >> $GITHUB_ENV
          fi

      - name: Print Final Branch Name
        run: |
          echo "Branch Name: ${branch_name:-$head_branch_name}"
          
  get-short-sha:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.get_sha.outputs.short_sha }}
    steps:
      - name: Show Short Git SHA
        id: get_sha
        run: echo "short_sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
        
  build:
    needs: [get-short-sha, determine-branch]
    uses: thunderbirdgit/gh-actions-wf/.github/workflows/nodejs-build.yml@main
    with:
      #service_name: "${{ env.service_name }}"
      service_name: "hw-ui-service"      
      short_sha: ${{ needs.get-short-sha.outputs.short_sha }}
      branch_name: ${{ needs.determine-branch.outputs.branch_name }}
